### ISSUE TITLE
Allow multi-word icon names to be searchable

### ISSUE THREAD

**Issue by johnmgriffith** [Esri/calcite-point-symbols#10]
In Point Symbols, currently, you need to type in the dash for the search to populate multi-word icons. If you were searching for `animal-safety` for example, if you searched "animal safety" it wouldn't appear. Please allow it to treat dashes as if they were spaces in the search.

**Comment by macandcheese** [comment]
Closing this as it is available in the developer site: https://developers.arcgis.com/calcite-design-system/icons/?library=Point%20Symbols&query=animal%20safety
