### ISSUE TITLE
Symbol Origins

### ISSUE THREAD

**Issue by spatialdude** [Esri/calcite-point-symbols#2]
Hi

This symbol set is great.

Is it possible to also add to the repo a file with x,y placement origins for each symbol?

This could be as simple as a 0 -> 1 values in each axis from from the top left corner within the icon's bounding box, that way it would work for all sizes of each symbol. e.g. 0.5, 0.5 = center, 0.5,1 = bottom center.

If the file is a simple CSV in the format - `<name>,<x-origin>,<y-origin>` - then it would be easy to read in code. The `name` would not include the size. -

`esri-pin-one,0.5,1`
`esri-pin-two,0.5,1`
`hexagon,0.5,0.5`

**Comment by sfrizzell** [comment]
A note back on this old issue...
We have made the point symbols to fit within a default circle container that could be applied to map symbols. The goal is to make the icon fully contained in the circle, even if it pushes the icon off-center in the artboard.

![bike-park-icon](https://github.com/user-attachments/assets/762fea60-c0cf-4521-85b2-2c4c068b1d78)

**Comment by sfrizzell** [comment]
@spatialdude your tool to set the center point for the icons seems to have resolved your need to define a functional middle of each icon. Is there any needed action on this issue or should we close it?

**Comment by spatialdude** [comment]
@sfrizzell This is awesome. Thanks no further action 👍
