### ISSUE TITLE
Typo fix and category need for `theft-from-coin-operated-machine-or-device` icon

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-point-symbols#23]
## Issue mitigation

1. The [`theft-from-coin-operated-machine-or-deviice`](https://github.com/Esri/calcite-point-symbols/blob/12351e721aa8307957dd7d1751c9de1d0672bd3c/icons/theft-from-coin-operated-machine-or-deviice-21.svg?plain=1) icon has a mis-spelling (should be device).
2. The icon's category is also depicted as uncategorized, but should be listed in "Law Enforcement" (crime classification)

## Background
Received via email on 4/13 from a Calcite user:

> Submitted on: Thu, 13 Apr 2023

> Regarding Web page: https://developers.arcgis.com/calcite-design-system/icons/?icon=theft-from-coin-operated-machine-or-deviice&library=Point%20Symbols&version=2.1.6
> Feedback: theft-from-coin-operated-machine-or-deviice icon is mis-spelled (should be device) and is in an uncategorized category when it should be in the Law Enforcement category (it is a crime classification)

**Comment by SkyeSeitz** [comment]
resolved in PR #24
