### ISSUE TITLE
Metadata Updates

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-point-symbols#26]
Awesome additions to the set in `2.1.7`! Noticed a couple things as I am previewing the changes in the Dev site icon search:

- Small casing mismatch on the 'Planning And Development' category with the recent updates. I try not to "fix" the metadata by auto-capitalizing as it may not always be intended, so if possible, would be great to get these updated in the metadata:
<img width="192" alt="Screen Shot 2023-05-08 at 10 08 20 AM" src="https://user-images.githubusercontent.com/4733155/236887032-60097a9b-d3a8-4cdd-b224-4bc4eba8ab45.png">

These should be "Disc" with a "c" :) 

<img width="1007" alt="Screen Shot 2023-05-08 at 10 13 04 AM" src="https://user-images.githubusercontent.com/4733155/236887600-4161bea4-76ba-4de2-a220-9de4579259ff.png">

Bicycle icons appear a bit distorted / squished (not sure if this intentional but wanted to share): 
<img width="410" alt="Screen Shot 2023-05-08 at 10 15 33 AM" src="https://user-images.githubusercontent.com/4733155/236888179-f87f25b2-2116-4aee-b756-cabb7d009510.png">

cc @SkyeSeitz

**Comment by nicklu10** [comment]
@macandcheese yes, these "distorted" icons are for pavement markings for Transportation solution, the markings on the roads are distorted in real life, we have to reflect that, Steve suggested we change the name to bicycle-lane-marking, which would be helpful. Nice catch on the Disc Golf, I'll fix these. And the capitalizing the category, let me look into how to get that changed, I'm not sure at the moment.

**Comment by macandcheese** [comment]
Thanks, makes sense re: bicycle, I was coming back to edit that comment as I realized those were all "road marking perspective". Re: category - should just be able to adjust the metadata in json. Thanks!

**Comment by SkyeSeitz** [comment]
+1 on changing the name to `bicycle-lane-marking`, especially since we may need a non-distorted bicycle icon in the future 👍🏽

**Comment by sfrizzell** [comment]
The bicycle icon was changes to bike-lane-21.svg
The "k" was changed to a "c" for the two disc golf icons that were referenced.

These changes were completed last year. Closing the issue now.
