### ISSUE TITLE
[Metadata] Typo in "annicniator-panel" name

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-point-symbols#34]
I think this should be "annunciator-panel"?

<img width="503" alt="Screenshot 2024-10-09 at 4 02 44 PM" src="https://github.com/user-attachments/assets/8188b0e9-fa16-4171-8b7f-840c9df30d78">

**Comment by arowles** [comment]
Hi @macandcheese I issued a fix in the latest pull request, so the icon should be spelled correctly and the changes should show when in the next update.

**Comment by macandcheese** [comment]
![Screenshot 2024-12-23 at 10 40 41 AM](https://github.com/user-attachments/assets/43f282a1-4214-4ed9-8543-9a9b178ac50f)

Looks good!
